# SAM FILE
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Lambda Function
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: src/
      Description: A simple Lambda function that returns a greeting.
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies:
        - AWSLambdaBasicExecutionRole